version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql.conf"
    environment:
      POSTGRES_DB: "tempdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: /var/lib/postgresql/data/db-files/
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tempdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
  redis:
    image: redis:7.2.1-alpine
    command: sh -c "
             mkdir /data/bases && 
             mkdir /data/log &&
             redis-server /usr/local/etc/redis/redis.conf"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis:/data
    ports:
      - 6379:6379
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
